"""Instrument universe — verbatim port of Repo 1's paper_engine.INDEX_LOT_SIZES
(index lot sizes) + config.INSTRUMENTS (strike steps / exchanges) +
stock_config.STOCKS. Keep in sync with Repo 1; do not hand-edit lot sizes."""

INDICES = [
    {"name": "NIFTY",     "strike_step": 50,  "fno_exchange": "NFO", "lot_size": 75},
    {"name": "BANKNIFTY", "strike_step": 100, "fno_exchange": "NFO", "lot_size": 15},
    {"name": "SENSEX",    "strike_step": 100, "fno_exchange": "BFO", "lot_size": 20},
]

# Copied verbatim from index-fno-signal-bot/src/stock_config.py STOCKS.
STOCKS = [
    {
        "name":          "RELIANCE",
        "equity_symbol": "RELIANCE",
        "sector":        "Energy/Conglomerate",
        "strike_step":   50,
        "lot_size":      250,
        "fno_exchange":  "NFO",
        "spot_exchange": "NSE",
    },
    {
        "name":          "ICICIBANK",
        "equity_symbol": "ICICIBANK",
        "sector":        "Private Banking",
        "strike_step":   20,
        "lot_size":      700,
        "fno_exchange":  "NFO",
        "spot_exchange": "NSE",
    },
    {
        "name":          "INFY",
        "equity_symbol": "INFY",
        "sector":        "IT",
        "strike_step":   20,
        "lot_size":      400,
        "fno_exchange":  "NFO",
        "spot_exchange": "NSE",
    },
    {
        "name":          "BAJFINANCE",
        "equity_symbol": "BAJFINANCE",
        "sector":        "NBFC",
        "strike_step":   100,
        "lot_size":      125,
        "fno_exchange":  "NFO",
        "spot_exchange": "NSE",
    },
    {
        "name":          "SUNPHARMA",
        "equity_symbol": "SUNPHARMA",
        "sector":        "Pharma",
        "strike_step":   20,
        "lot_size":      400,
        "fno_exchange":  "NFO",
        "spot_exchange": "NSE",
    },
    {
        "name":          "LT",
        "equity_symbol": "LT",
        "sector":        "Engineering/Infra",
        "strike_step":   50,
        "lot_size":      175,
        "fno_exchange":  "NFO",
        "spot_exchange": "NSE",
    },
    {
        "name":          "SBIN",
        "equity_symbol": "SBIN",
        "sector":        "PSU Banking",
        "strike_step":   10,
        "lot_size":      750,
        "fno_exchange":  "NFO",
        "spot_exchange": "NSE",
    },
    {
        "name":          "BHARTIARTL",
        "equity_symbol": "BHARTIARTL",
        "sector":        "Telecom",
        "strike_step":   20,
        "lot_size":      475,
        "fno_exchange":  "NFO",
        "spot_exchange": "NSE",
    },
    {
        "name":          "TATASTEEL",
        "equity_symbol": "TATASTEEL",
        "sector":        "Metals",
        "strike_step":   2.5,
        "lot_size":      2750,
        "fno_exchange":  "NFO",
        "spot_exchange": "NSE",
    },
    {
        "name":          "ASIANPAINT",
        "equity_symbol": "ASIANPAINT",
        "sector":        "Paints/Consumer",
        "strike_step":   20,
        "lot_size":      250,
        "fno_exchange":  "NFO",
        "spot_exchange": "NSE",
    },
    {
        "name":          "AXISBANK",
        "equity_symbol": "AXISBANK",
        "sector":        "Private Banking",
        "strike_step":   10,
        "lot_size":      625,
        "fno_exchange":  "NFO",
        "spot_exchange": "NSE",
    },
    {
        "name":          "MARUTI",
        "equity_symbol": "MARUTI",
        "sector":        "Auto",
        "strike_step":   100,
        "lot_size":      50,
        "fno_exchange":  "NFO",
        "spot_exchange": "NSE",
    },
    {
        "name":          "CIPLA",
        "equity_symbol": "CIPLA",
        "sector":        "Pharma",
        "strike_step":   10,
        "lot_size":      375,
        "fno_exchange":  "NFO",
        "spot_exchange": "NSE",
    },
    {
        "name":          "HINDALCO",
        "equity_symbol": "HINDALCO",
        "sector":        "Metals",
        "strike_step":   10,
        "lot_size":      700,
        "fno_exchange":  "NFO",
        "spot_exchange": "NSE",
    },
]

ALL_INSTRUMENT_NAMES = [i["name"] for i in INDICES] + [s["name"] for s in STOCKS]
